// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFX_kjTkwXVsRaRyNZjOaK1GhXHX9s89o',
    appId: '1:367198293006:web:ea9331337872b7aa53805f',
    messagingSenderId: '367198293006',
    projectId: 'nutriplan-campus',
    authDomain: 'nutriplan-campus.firebaseapp.com',
    storageBucket: 'nutriplan-campus.firebasestorage.app',
    measurementId: 'G-R8SEYPWTNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKMZfXHjizQlYeYN_zzShqFCmkdQShl4M',
    appId: '1:367198293006:android:20ab6b91fd006c3a53805f',
    messagingSenderId: '367198293006',
    projectId: 'nutriplan-campus',
    storageBucket: 'nutriplan-campus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH1nZyzCvgp_C9c9hcXlz18vAFaqeXFSM',
    appId: '1:367198293006:ios:acd288a7fcd205bf53805f',
    messagingSenderId: '367198293006',
    projectId: 'nutriplan-campus',
    storageBucket: 'nutriplan-campus.firebasestorage.app',
    iosBundleId: 'com.example.nutriplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH1nZyzCvgp_C9c9hcXlz18vAFaqeXFSM',
    appId: '1:367198293006:ios:acd288a7fcd205bf53805f',
    messagingSenderId: '367198293006',
    projectId: 'nutriplan-campus',
    storageBucket: 'nutriplan-campus.firebasestorage.app',
    iosBundleId: 'com.example.nutriplan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFX_kjTkwXVsRaRyNZjOaK1GhXHX9s89o',
    appId: '1:367198293006:web:14dc4a55a71dcf9753805f',
    messagingSenderId: '367198293006',
    projectId: 'nutriplan-campus',
    authDomain: 'nutriplan-campus.firebaseapp.com',
    storageBucket: 'nutriplan-campus.firebasestorage.app',
    measurementId: 'G-FG7NLJX9G6',
  );
}
